app <- ShinyDriver$new("../../")
app$snapshotInit("test1")

app$setInputs(fragment_types_input = c("M", "M*", "a", "b", "c", "x", "y", "y-2", "z", "z-1", "d", "v", "w", "b+H2O"))
app$setInputs(sequence_input = "ACDEFGHIKL-12.0MNPQRSs-3TtUVWYy+15.")
app$snapshot()
app$setInputs(deuterium_exchange_input = TRUE)
app$snapshot()
app$setInputs(polarity_input = "click")
app$snapshot()
app$setInputs(charge_input = 3)
app$snapshot()
app$setInputs(max_charge_input = "Selected Charge")
app$snapshot()
